name: Container

on:
  push:
#    tags:
#    - "*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Login Build Push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          make
          docker tag netapp/trident:26.02.0-custom ghcr.io/${{ github.repository_owner }}/netapp/trident:26.02.0-custom
          docker push ghcr.io/${{ github.repository_owner }}/netapp/trident:26.02.0-custom
